{{- /* 文件说明：要求三节点集群在主动驱逐期间至少保留两个可用 Pod，以维持多数派。 */ -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "uino-elasticsearch.fullname" . }}
  labels:
    {{- include "uino-elasticsearch.labels" . | nindent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      {{- include "uino-elasticsearch.selectorLabels" . | nindent 6 }}
